### ISSUE TITLE
License

### ISSUE THREAD

**Issue by giorgiofellipe** [jbeurel/angular-parse-boilerplate#8]
Does it have a license? I've made a clone and I'm developing on it and didn't see any license.

**Comment by jbeurel** [comment]
Hi @giorgiofellipe ! 

MIT Licence. (Thanks @kosssi)

Does your project is opensource ? Don't hesitate to share your work or make some Issues/PR if the boilerplate has some missing features :-)

**Comment by giorgiofellipe** [comment]
Thanks @jbeurel!

Yes, it is. I'll do if there's something missing.
